services:
  postgres-db:
    image: postgres:15.5-alpine
    container_name: postgres-db
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - ./db/sql/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      POSTGRES_DB: healenium
      POSTGRES_USER: healenium_user
      POSTGRES_PASSWORD: healenium_password

  healenium:
    image: healenium/hlm-backend:3.5.0
    container_name: healenium
    restart: on-failure
    ports:
      - "7878:7878"
    depends_on:
      - postgres-db
    environment:
      SPRING_POSTGRES_DB: healenium
      SPRING_POSTGRES_SCHEMA: healenium
      SPRING_POSTGRES_USER: healenium_user
      SPRING_POSTGRES_PASSWORD: healenium_password
      SPRING_POSTGRES_DB_HOST: postgres-db
      KEY_SELECTOR_URL: "false"
      COLLECT_METRICS: "true"
      FIND_ELEMENTS_AUTO_HEALING: "false"
      HLM_LOG_LEVEL: info

  selector-imitator:
    image: healenium/hlm-selector-imitator:1.6
    container_name: selector-imitator
    restart: on-failure
    ports:
      - "8000:8000"